version: '3'
services:
  mysql:
    # https://hub.docker.com/_/mysql
    image: mysql:latest
    container_name: proyecto-daw-mysql
    restart: unless-stopped
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./volumes/initdb/:/docker-entrypoint-initdb.d
      - ./volumes/mysql:/var/lib/mysql

  phpmyadmin:
    # https://hub.docker.com/_/phpmyadmin
    image: phpmyadmin:latest
    container_name: proyecto-daw-phpmyadmin
    restart: unless-stopped
    ports:
      - 8100:80
    environment:
      PMA_ARBITRARY: 1
      MYSQL_ROOT_PASSWORD: root

  store-api:
    build: .
    container_name: proyecto-daw-store-api
    restart: unless-stopped
    volumes:
      - ./StoreAPI:/StoreAPI
    network_mode: host
    depends_on:
      - mysql

